// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import FlatpickrController from "controllers/flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ToggleController from "controllers/toggle_controller"
application.register("toggle", ToggleController)

import SpeechController from "./speech_controller"
application.register("speech", SpeechController)
